stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: skill-manager-front

containerization:
  stage: containerization
  script:
    - docker build -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME} .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}

deployment:
  stage: deployment
  script:
    - kubectl apply -f deployment.yml
    - kubectl rollout restart deployment/${APPLICATION_NAME}-deployment
  environment:
    name: staging
